apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gb-demo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
    - hosts:
      - demo.reportingapp.com
      secretName: gb-demo-secret-tls
    - hosts:
      - minikube
      secretName: gb-minikube-secret-tls
  rules:
    - host: demo.reportingapp.com
      http:
        paths:
          - path: /search
            backend:
              serviceName: gb-api-search
              servicePort: 443
          - path: /report
            backend:
              serviceName: gb-api-report
              servicePort: 443
    - host: minikube
      http:
        paths:
          - path: /search
            backend:
              serviceName: gb-api-search
              servicePort: 443
          - path: /report
            backend:
              serviceName: gb-api-report
              servicePort: 443
