apiVersion: v1
kind: Pod
metadata:
  name: {{ template "prefix" . }}-gen-data
  labels:
    app: {{ .Values.appNameLabel }}
spec:
  containers:
  - name: {{ template "prefix" . }}-gen-data
    image: {{ .Values.dockerRegistry}}/gen-data:{{ template "gbVersion" . }}
    resources:
      requests:
        memory: "500M"
        cpu: "100m"
      limits:
        memory: "500M"
        cpu: "500m"
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    env:
      - name: JAVA_OPTS
        value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      - name: COUNT
        value: "100000"
      - name: BATCH_SIZE
        value: "5000"
      - name: ES_HOST
        value: {{ template "prefix" . }}-elasticsearch
      - name: ES_PORT
        value: "80"
  restartPolicy: OnFailure