FROM debian:9-slim

RUN apt-get update && apt-get upgrade -y --no-install-recommends \
	&& apt-get install -y ca-certificates wget xz-utils libxrender1 libxt6 libxtst6 fontconfig \
	&& wget https://github.com/peteretelej/wkhtmltopdf-docker/releases/download/0.0.1/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
	&& tar -xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
	&& cp wkhtmltox/bin/wkhtmltopdf /usr/local/bin \
	&& rm -rf wkhtmltox* \
	&& apt-get purge -y --auto-remove wget xz-utils \
	&& rm -rf /var/lib/apt/lists/*

COPY Rocket.toml /
COPY target/x86_64-unknown-linux-musl/release/api-report /
COPY templates/* /templates/
COPY demokeys /demokeys/

CMD ["/api-report"]