gateways:
  istio-ingressgateway:
    type: NodePort
  istio-egressgateway:
    type: NodePort

grafana:
  enabled: true

kiali:
  enabled: true
  dashboard:
    grafanaURL: http://localhost:3000 # check this time