admin:
  cluster:
    - all
  indices:
    - names: '*'
      privileges:
        - all
ingestion:
  indices:
    - names: '*'
      privileges:
        - index
        - read
        - view_index_metadata
        - create_index
        - manage
manager:
  indices:
    - names: '*'
      privileges:
        - index
        - read
        - view_index_metadata
        - create_index
      field_security:
        grant:
          - color
          - sold
          - make
guest:
  indices:
    - names: '*'
      privileges: